### ISSUE TITLE
Trader bob does not have the parameters.

### ISSUE THREAD

**Issue by FitchKrause** [arramus/A21-OldWestMigration#1]
Trader bob(trader_oldwest_bob.xml) does not have the following parameters:
1) TraderAreaProtect - a trigger that protects against the destruction of the trader's territory by a player or a zombie (by default, these values are 0,0,0, but it seems to me that it takes values from the size of the prefab itself or the TradeAreaTeleportSize trigger).
2) TradeAreaTeleportSize - a trigger for teleporting a player outside the store.
3) TraderAreaTeleportCenter - coordinates of the location of the TradeAreaTeleportSize trigger.

An easy way to fix a trader is to copy three lines (TraderAreaProtect, TradeAreaTeleportSize, TraderAreaTeleportCenter) from the original trader (from alpha 20) and paste into trader_oldwest_bob.xml after the line <property name="TraderArea" value="True" />

For myself, I returned the original trader by editing the prefab for the needs of generation in the city.

**Comment by arramus** [comment]
Thank you for sharing your findings of parameters 1., 2., and 3. and also an explanation of how they are hooked up to function. 

A21 trader_hugh has neither 2. nor 3. on your list of parameters but it does have 1.
A21 trader_rekt has 1., 2., and 3.
A21 trader_joel has 1., 2., and 3.
A21 trader_jen has 1., 2., and 3.
A21 trader_bob has 1., 2., and 3. It will also appear in a regular 60 x 60 spot when using this mod.

Please also note that A21 trader_hugh and A21 trader_oldwest_bob both have the new A21 Trader Teleports Volumes, as do they all.

Feel free to share the discrepancy for trader_hugh in the Bug area of the 7D2D Forum since it does not match the 'dependencies' suggested in this report. I look forward to hearing the feedback, which will in turn allow trader_oldwest_bob to follow the 'correct' A21 hookup flow.

https://community.7daystodie.com/a21-bugs-main/bug-pool/how-to-report-bugs-found-in-a21-r4/

**Comment by arramus** [comment]
This issue is being closed for now. The discrepancy does not appear to have been reported after checking the requisite areas. A20 and A21 follows a differing format for how the traders handle their environment and there will be no roll back to A20 values unless necessary. Remnant code is a common feature in progressive Alpha builds and time will tell on necessity.
